const types = {
  // assignments
  LOAD_ASSIGNMENTS_SUCCESS: "LOAD_ASSIGNMENTS_SUCCESS",
  CREATE_ASSIGNMENT_SUCCESS: "CREATE_ASSIGNMENT_SUCCESS",
  DELETE_ASSIGNMENT_SUCCESS: "DELETE_ASSIGNMENT_SUCCESS",
  UPDATE_ASSIGNMENT_SUCCESS: "UPDATE_ASSIGNMENT_SUCCESS",

  // classes
  LOAD_CLASSES_SUCCESS: "LOAD_CLASSES_SUCCESS",
  CREATE_CLASS_SUCCESS: "CREATE_CLASS_SUCCESS",
  DELETE_CLASS_SUCCESS: "DELETE_CLASS_SUCCESS",
  UPDATE_CLASS_SUCCESS: "UPDATE_CLASS_SUCCESS"
};

export default types;