const types = {
  // assignments
  LOAD_ASSIGNMENTS_SUCCESS: "LOAD_ASSIGNMENTS_SUCCESS",
  CREATE_ASSIGNMENT_SUCCESS: "CREATE_ASSIGNMENT_SUCCESS",
  DELETE_ASSIGNMENT_SUCCESS: "DELETE_ASSIGNMENT_SUCCESS",
  UPDATE_ASSIGNMENT_SUCCESS: "UPDATE_ASSIGNMENT_SUCCESS"
};

export default types;